compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@essex/webpack-config@*":
    peerDependencies:
      typescript: "*"
      worker-loader: "*"
  react-cookie-banner@*:
    peerDependencies:
      prop-types: "*"
  styled-components@*:
    dependencies:
      react-is: ^16

yarnPath: .yarn/releases/yarn-4.0.0-rc.50.cjs
