
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"


packageExtensions:
  "lineupjs@*":
    dependencies:
        "tslib" : "*"
    peerDependencies:
      "tslib" : "*"
  "@essex/webpack-config@*":
    peerDependencies:
      typescript: "*"
      worker-loader: "*"
  "styled-components@*":
    dependencies:
      "react-is": "^16"
yarnPath: .yarn/releases/yarn-2.4.0.cjs
